name = "rust"
title = "Rust Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
    "/fundamentals/connections",
    "/fundamentals/crud"
    ]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB Rust Driver"
driver-short = "Rust driver"
server = "MongoDB Server"
docs-branch = "master" # always set this to the docs branch (i.e. master, v2.6, v2.5, etc.)
version = "2.6.0" # always set this to the driver version (i.e. 2.6.0, 2.5.0, etc.)
api = "https://docs.rs/mongodb/{+version+}/mongodb"
stable-api = "Stable API"